#!/usr/bin/env bash

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# prompt successful message
echo_succ() {
	echo -e "${GREEN}*$1*${NC}"
}

# prompt failed message
echo_fail() {
	echo -e "${RED}*$1*${NC}"
}

exist_cmd() {
	if type $1 >/dev/null 2>&1; then
		return 0
	else
		return 1
	fi
}

# detect OS type
if [[ $(uname) = "Darwin" ]]; then
	OSTYPE="OSX"
	if ! exist_cmd brew; then
		# install Homebrew
		/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	fi
	INSTALL_PREFIX="brew"
elif [[ $(cat /etc/issue | head -n 1 | cut -c1-6) == "Ubuntu" ]]; then
	OSTYPE="Ubuntu"
	INSTALL_PREFIX="sudo apt-get install -y"
else
	echo_fail "Unsupported OS Type!"
	exit 1
fi

while true; do
	echo
	echo "========================================="
	echo "What do you want to do? (ENTER q to exit)"
	echo "1. copy ssh keys to another machine"
	echo "2. prepare *nix working environment"

	read sel

	if [[ "$sel" == "1" ]]; then
		if [[ "$OSTYPE" == "OSX" ]] && ! exist_cmd ssh-copy-id; then
			$INSTALL_PREFIX ssh-copy-id
		fi
		echo "Please input remote-host-addr:"
		read remote_host
		echo "ssh-copy-id -i ~/.ssh/id_rsa.pub $remote_host"
		ssh-copy-id -i ~/.ssh/id_rsa.pub $remote_host
	elif [[ "$sel" == "2" ]]; then
		# install git
		if ! exist_cmd git; then
			echo "installing git..."
			$INSTALL_PREFIX git
		fi
		# install vim
		if  ! exist_cmd vim; then
			echo "installing vim..."
			$INSTALL_PREFIX vim 
		fi
		# install z-shell
		if  ! exist_cmd zsh; then
			echo "installing zsh..."
			$INSTALL_PREFIX zsh 
		fi
		# install oh-my-zsh
		if [[ ! -d ~/.oh-my-zsh ]]; then
			sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
		fi
		# install Tmux
		if  ! exist_cmd tmux; then
			echo "installing tmux..."
			$INSTALL_PREFIX tmux
		fi
		# apply configuration to zsh, vimperatorrc, vim, tmux
		if [[ ! -d ~/chief_config ]]; then
			cd ~
			if [[ $OSTYPE == "Ubuntu" ]]; then
				echo "git clone -b ubuntu https://git.ustclug.org/jkad/chief_config.git"
				git clone -b ubuntu https://git.ustclug.org/jkad/chief_config.git
			else
				echo "git clone https://git.ustclug.org/jkad/chief_config.git"
				git clone https://git.ustclug.org/jkad/chief_config.git
			fi
			cd chief_config
			cp ./zshrc ~/.zshrc
			cp ./vimperatorrc ~/.vimperatorrc
			cp ./vimrc ~/.vimrc 
			cp ./tmux.conf ~/.tmux.conf 
		fi
		echo_succ "Successfully done"
	elif [[ "$sel" == "q" ]]; then
		exit 1
	else
		echo_fail "Illegal input!"
	fi
done

